name: Tests
on:
  push:
    branches:
      - main
jobs:
  frisbyTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm ci -C functions
      - name: Run firebase emulators
        run: npm run serve -C functions &
      - name: run frisby
        id: frisby
        run: npm run frisby -C functions
  #     - name: Notify frisby
  #       uses: 8398a7/action-slack@v3.8.0
  #       with:
  #         status: ${{ steps.frisby.outcome }}
  #         author_name: frisby テストの実行結果
  #         fields: repo,message,commit,author,job,took,eventName
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       if: always()
  # k6Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #     - name: install k6
  #       run: |
  #         curl https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
  #       working-directory: ./functions
  #     - name: install firebase-tools
  #       run: npm install -g firebase-tools
  #     - name: install node_modules
  #       run: npm ci -C functions
  #     - name: run k6
  #       id: k6
  #       run: npm run k6 -C functions
  #     - name: Notify k6
  #       uses: 8398a7/action-slack@v3.8.0
  #       with:
  #         status: ${{ steps.k6.outcome }}
  #         author_name: k6 テストの実行結果
  #         fields: repo,message,commit,author,job,took,eventName
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  #       if: always()
  zapTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: install zap
        run: docker pull owasp/zap2docker-weekly
        working-directory: ./functions
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm ci -C functions
      # - name: Run firebase emulators
      #   run: npm run serve -C functions &
      # - name: Action API Scan
      #   uses: zaproxy/action-api-scan@v0.1.0
      #   with:
      #     docker_name: 'owasp/zap2docker-stable'
      #     format: openapi
      #     target: functions/openapi.json
      #   continue-on-error: true
      # - name: Action API Scan
      #   run: npm run logs -C functions
      - name: run zap
        id: zap
        run: npm run zap -C functions
        continue-on-error: true
      # - name: Notify k6
      #   uses: 8398a7/action-slack@v3.8.0
      #   with:
      #     status: ${{ steps.k6.outcome }}
      #     author_name: k6 テストの実行結果
      #     fields: repo,message,commit,author,job,took,eventName
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()