name: Test
on:
  push:
    branches:
      - main
jobs:
  frisbyTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: install node_modules
        run: npm ci -C functions
      - name: run frisby
        id: frisby
        run: npm run build && firebase emulators:exec 'jest' --only functions -C functions